### ISSUE TITLE
能详细说明下怎么禁用XHCI1，非常感谢

### ISSUE THREAD

**Issue by caifenglin** [ztx6506/RedmiBook-Pro-14-AMD-hackintosh#2]
下载了那个软件，也通过u盘进入管理页面，但是有些选项进去之后都是横线，只看到管理设备和管理引导的页面，没有看到具体怎么禁用XHCI1，希望老哥帮忙指引下

**Comment by Tinsiag** [comment]
进去之后都是横线的话,将语言改为English即可
![IMG_1670](https://github.com/ztx6506/RedmiBook-Pro-14-AMD-hackintosh/assets/56108128/a7f5a0bd-e177-415e-838d-dff6c1048f24)
# **禁用XHCI1之后 笔记本右边的USB口将不可用**
# 教程

## 进入 Device Manager / AMD CBS / FCH Common Options/ USB ·····/XHCI1 contr···· 改成disabled 即可

## ![IMG_1672](https://github.com/ztx6506/RedmiBook-Pro-14-AMD-hackintosh/assets/56108128/90db13a3-1065-450a-9d12-6493b4d77cf7)
### ![IMG_1673](https://github.com/ztx6506/RedmiBook-Pro-14-AMD-hackintosh/assets/56108128/bf4f508f-7111-48c1-83c4-5c0363d41b37)
## ![IMG_1674](https://github.com/ztx6506/RedmiBook-Pro-14-AMD-hackintosh/assets/56108128/33b339e0-85db-477b-a37c-142a3e81c809)
## ![IMG_1675](https://github.com/ztx6506/RedmiBook-Pro-14-AMD-hackintosh/assets/56108128/fac49cfa-985d-4725-8a63-a511a221a01e)
## 按esc 退出 退到如下图 按y 继续退出 
## ![IMG_1676](https://github.com/ztx6506/RedmiBook-Pro-14-AMD-hackintosh/assets/56108128/1835b988-4bad-44c8-b34c-a61c03085608)

## 退到主界面之后 选择Continue 保存退出 就ok 了
![IMG_1677](https://github.com/ztx6506/RedmiBook-Pro-14-AMD-hackintosh/assets/56108128/236f9c73-14c0-4517-90d7-aecece84c772)
